forageSystem.forageDefinitions['Plantain'] = nil
forageSystem.forageDefinitions['Comfrey'] = nil
forageSystem.forageDefinitions['CommonMallow'] = nil
forageSystem.forageDefinitions['LemonGrass'] = nil
forageSystem.forageDefinitions['BlackSage'] = nil

--[[
forageSystem.forageDefinitions['MushroomGeneric1'].malusMonths = {}
forageSystem.forageDefinitions['MushroomGeneric1'].months = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
forageSystem.forageDefinitions['MushroomGeneric1'].validMonths = {
    [1] = 10,
    [2] = 10,
    [3] = 10,
    [4] = 10,
    [5] = 10,
    [6] = 10,
    [7] = 10,
    [8] = 10,
    [9] = 10,
    [10] = 10,
    [11] = 10,
    [12] = 10,
}]]


local function generateMedicinalPlantSeedsDefs()
    local itemDefs = {
        PlantainSeeds = {
            type = "Base.BroadleafPlantainSeed",
            minCount = 2,
            maxCount = 5,
            xp = 15,
            recipes = { "Herbalist" },
            categories = { "MedicinalPlants" },
            zones = {
                Forest          = 10,
                PHForest        = 10,
                PRForest        = 10,
                BirchForest     = 10,
                OrganicForest   = 10,
                DeepForest      = 15,
                Vegitation      = 5,
                FarmLand        = 5,
                Farm            = 5,
            },
            months = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            altWorldTexture = forageSystem.worldSprites.wildPlants,
            spawnFuncs = { forageSystem.doGenericItemSpawn },
        },
        ComfreySeed = {
            type = "Base.ComfreySeed",
            minCount = 2,
            maxCount = 5,
            xp = 15,
            recipes = { "Herbalist" },
            categories = { "MedicinalPlants" },
            zones = {
                Forest          = 40,
                PHForest        = 40,
                PRForest        = 40,
                BirchForest     = 40,
                OrganicForest   = 40,
                DeepForest      = 45,
                Vegitation      = 15,
                FarmLand        = 15,
                Farm            = 15,
            },
            months = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            altWorldTexture = forageSystem.worldSprites.vines,
            spawnFuncs = { forageSystem.doGenericItemSpawn },
        },
        CommonMallowSeed = {
            type = "Base.CommonMallowSeed",
            minCount = 2,
            maxCount = 5,
            xp = 15,
            recipes = { "Herbalist" },
            categories = { "MedicinalPlants" },
            zones = {
                Forest          = 10,
                PHForest        = 10,
                PRForest        = 10,
                BirchForest     = 10,
                OrganicForest   = 10,
                DeepForest      = 15,
                Vegitation      = 5,
                FarmLand        = 5,
                Farm            = 5,
            },
            months = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            spawnFuncs = { forageSystem.doGenericItemSpawn },
            altWorldTexture = forageSystem.worldSprites.vines,
        },
        LemonGrassSeed = {
            type = "Base.LemonGrassSeed",
            minCount = 2,
            maxCount = 5,
            xp = 5,
            categories = { "MedicinalPlants" },
            zones = {
                Forest          = 10,
                PHForest        = 10,
                PRForest        = 10,
                BirchForest     = 10,
                OrganicForest   = 10,
                DeepForest      = 15,
                Vegitation      = 5,
                FarmLand        = 5,
                Farm            = 5,
            },
            months = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            spawnFuncs = { forageSystem.doGenericItemSpawn },
            altWorldTexture = getTexture("media/textures/Foraging/worldSprites/lemongrass_worldSprite.png"),
        },
        BlackSageSeed = {
            type = "Base.BlackSageSeed",
            minCount = 2,
            maxCount = 5,
            xp = 15,
            recipes = { "Herbalist" },
            categories = { "MedicinalPlants" },
            zones = {
                Forest          = 10,
                PHForest        = 10,
                PRForest        = 10,
                BirchForest     = 10,
                OrganicForest   = 10,
                DeepForest      = 15,
                Vegitation      = 5,
                FarmLand        = 5,
                Farm            = 5,
            },
            months = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            spawnFuncs = { forageSystem.doGenericItemSpawn },
            altWorldTexture = forageSystem.worldSprites.wildPlants,
        },
    }
    for itemName, itemDef in pairs(itemDefs) do
        forageSystem.addForageDef(itemName, itemDef);
    end
end

local function generateMushroomsExtraDefs()
    local itemDefs = {
        MushroomGeneric10 = {
            type = "Base.MushroomGeneric1",
            minCount = 2,
            maxCount = 5,
            xp = 2,
            categories = { "Mushrooms" },
            zones = {
                Forest          = 100,
                PHForest        = 100,
                PRForest        = 100,
                BirchForest     = 100,
                OrganicForest   = 100,
                DeepForest      = 150,
                Vegitation      = 50,
                FarmLand        = 50,
                Farm            = 50,
            },
            months = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            bonusMonths = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            poisonChance = 10,
            poisonPowerMin = 5,
            poisonPowerMax = 50,
            poisonDetectionLevel = 5,
            spawnFuncs = { forageSystem.doPoisonItemSpawn, forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
        },
        MushroomGeneric11 = {
            type = "Base.MushroomGeneric2",
            minCount = 2,
            maxCount = 5,
            xp = 2,
            categories = { "Mushrooms" },
            zones = {
                Forest          = 100,
                PHForest        = 100,
                PRForest        = 100,
                BirchForest     = 100,
                OrganicForest   = 100,
                DeepForest      = 150,
                Vegitation      = 50,
                FarmLand        = 50,
                Farm            = 50,
            },
            months = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            bonusMonths = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            poisonChance = 10,
            poisonPowerMin = 5,
            poisonPowerMax = 50,
            poisonDetectionLevel = 5,
            spawnFuncs = { forageSystem.doPoisonItemSpawn, forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
        },
        MushroomGeneric12 = {
            type = "Base.MushroomGeneric3",
            minCount = 2,
            maxCount = 5,
            xp = 2,
            categories = { "Mushrooms" },
            zones = {
                Forest          = 100,
                PHForest        = 100,
                PRForest        = 100,
                BirchForest     = 100,
                OrganicForest   = 100,
                DeepForest      = 150,
                Vegitation      = 50,
                FarmLand        = 50,
                Farm            = 50,
            },
            months = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            bonusMonths = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            poisonChance = 10,
            poisonPowerMin = 5,
            poisonPowerMax = 50,
            poisonDetectionLevel = 5,
            spawnFuncs = { forageSystem.doPoisonItemSpawn, forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
        },
        MushroomGeneric13 = {
            type = "Base.MushroomGeneric4",
            minCount = 2,
            maxCount = 5,
            xp = 2,
            categories = { "Mushrooms" },
            zones = {
                Forest          = 100,
                PHForest        = 100,
                PRForest        = 100,
                BirchForest     = 100,
                OrganicForest   = 100,
                DeepForest      = 150,
                Vegitation      = 50,
                FarmLand        = 50,
                Farm            = 50,
            },
            months = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            bonusMonths = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            poisonChance = 10,
            poisonPowerMin = 5,
            poisonPowerMax = 50,
            poisonDetectionLevel = 5,
            spawnFuncs = { forageSystem.doPoisonItemSpawn, forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
        },
        MushroomGeneric14 = {
            type = "Base.MushroomGeneric5",
            minCount = 2,
            maxCount = 5,
            xp = 2,
            categories = { "Mushrooms" },
            zones = {
                Forest          = 100,
                PHForest        = 100,
                PRForest        = 100,
                BirchForest     = 100,
                OrganicForest   = 100,
                DeepForest      = 150,
                Vegitation      = 50,
                FarmLand        = 50,
                Farm            = 50,
            },
            months = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            bonusMonths = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12 },
            poisonChance = 10,
            poisonPowerMin = 5,
            poisonPowerMax = 50,
            poisonDetectionLevel = 5,
            spawnFuncs = { forageSystem.doPoisonItemSpawn, forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
        },
    }
    for itemName, itemDef in pairs(itemDefs) do
        forageSystem.addForageDef(itemName, itemDef);
    end
end

generateMedicinalPlantSeedsDefs()

generateMushroomsExtraDefs()
